### ISSUE TITLE
[Bug]: Wrong download link for Pro version

### ISSUE THREAD

**Issue by rixocz** [goreleaser/goreleaser-azure-devops-extension#1130]
### What happened?

From version 2.7.0 gorelaser and goreleaser-pro is under one release.

For `latest` verison is generated download link 
`https://github.com/goreleaser/goreleaser-pro/releases/download/v2.8.1-pro/goreleaser-pro_Linux_x86_64.tar.gz` 
but should be 
`https://github.com/goreleaser/goreleaser-pro/releases/download/v2.8.1/goreleaser-pro_Linux_x86_64.tar.gz`

version dir is without `-pro`

### How can we reproduce this?

```yaml
- task: goreleaser@0
  inputs:
    version: 'latest'
    distribution: 'goreleaser-pro'
    args: ''
    workdir: '$(Build.SourcesDirectory)/$(TOOL_DIR)'
  env:
    GORELEASER_KEY: $(goreleaser-key)
```

### goreleaser-azure-devops-extension version

```bash
0.2.0
```

### Search

- [x] I did search for other open and closed issues before opening this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
